import "./globals.css";
import { Epilogue } from "next/font/google";

const epilog = Epilogue({
  subsets: ["latin"],
  weight: ["500", "700"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${epilog.className}`}>
      <body className="bg-almostWhite">{children}</body>
    </html>
  );
}
